---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: clone repo on host
    git: repo=https://github.com/MamthaM/projCert.git dest=/tmp/gitrepo
  - name: Pull image from docker hub
    command: docker pull devopsedu/webapp
  - name: Build docker container from Image
    command: docker run -itd -P devopsedu/webapp
